version: '3'
services:
  azure-vote-back:
    build: ./azure-vote-back
    image: azure-vote-back
    container_name: azure-vote-back
    ports:
        - "6379:6379"

  azure-vote-front:
    build:
      context: ../
      dockerfile: ./azure-vote-app/azure-vote/Dockerfile
    image: azure-vote-front
    container_name: azure-vote-front
    environment:
      REDIS: azure-vote-back
    ports:
        - "8080:80"
